### PR TITLE
Descriptions of the type of the Patterns Done!

### LINKED ISSUE #3: Descrição dos tipos de Padrões

### PR DESCRIPTION
**Pull request by pedrotst**
closes #3

### CODE REVIEW

**Comment by ivandrofly** [comment]
What I suggest is to have at least two people to review a pull request before it's merged to avoid typos or some kinds of errors... /cc @pedrotst

**Comment by ivandrofly** [comment]
One more thing please make sure all the commits go through a pull-request unless is something very small

**Comment by pedrotst** [comment]
Oh yeah, nice. Sorry about that.

I also suggest let's keep the workflow opening/closing issues so we know who is working on what.

**Comment by pedrotst** [comment]
I would revert these pull requests, but looks like a lot of trouble, so please open a new pull request with the changes.

Sorry again for the trouble.

**Pull request merged**
